correcting material parameters
icub-tech-iit/cad-libraries pull request #142
Opened 2023-02-16 12:22 UTC by Mick3Lozzo

Correcting parameters according to

![Screenshot 2023-02-16 112037](https://user-images.githubusercontent.com/15085666/219363339-010f4fdd-f72b-4e32-8a2c-57bb206ec7a1.jpg)

See also [this page](https://www.azom.com/properties.aspx?ArticleID=1595).

2023-02-17 16:05 UTC, fiorisi commented
Thanks @Mick3Lozzo. Few points:
- why [here](https://github.com/icub-tech-iit/cad-libraries/pull/142/files#diff-d1f410db3f08870352ea99b8bf9d1412b5ac16bae382f24001ff011cff0ba3b9R27) there ist written ergal?
- I would provide also a material descriptio. See [here](https://github.com/icub-tech-iit/cad-libraries/pull/142/files#diff-d1f410db3f08870352ea99b8bf9d1412b5ac16bae382f24001ff011cff0ba3b9R7)
- I think that we can't manufacture sheetmetal parts with this material. Where did you take the `PTC_INITIAL_BEND_Y_FACTOR` value? The same for `PTC_BEND_TABLE` 
- Do you have a source for the value of the parameter `PTC_MASS_DENSITY` ?

2023-02-17 16:07 UTC, fiorisi requested changes
@Mick3Lozzo see the points in the previous comment.

2023-02-20 14:28 UTC, Mick3Lozzo commented
![](https://user-images.githubusercontent.com/15085666/220133205-1f0ce7d9-2465-4005-bbbc-dd82a66c5b83.png)

For NdFeB magnets, the physical properties are different than for 100% Neodymium.  
  
See [this link](https://e-magnetsuk.com/introduction-to-neodymium-magnets/characteristics-of-ndfeb-magnets/).

2023-02-20 14:29 UTC, fiorisi commented
> > Thanks @Mick3Lozzo. Few points:
> > 
> > * Do you have a source for the value of the parameter `PTC_MASS_DENSITY` ?
> 
> It's in the datasheet @fiorisi.
> 
> ![](https://user-images.githubusercontent.com/15085666/220129561-278a170e-6a9b-4d5f-bf38-22e196c8e16b.png)

7.5 Kg for cube meter? Seems low, in the file you actually set it to 7.5 g / cm^3

2023-02-20 14:35 UTC, Mick3Lozzo commented
> 7.5 Kg for cube meter? Seems low, in the file you actually set it to 7.5 g / cm^3

[In the other table](https://user-images.githubusercontent.com/15085666/220133205-1f0ce7d9-2465-4005-bbbc-dd82a66c5b83.png), I saw 7.5 g/cc. I suppose cc is cm^3 @fiorisi.

2023-02-20 14:55 UTC, Mick3Lozzo commented
@fiorisi for all the materials We have `Initial Bend Y-Factor = 0.5`

We can consider it as a sort of default value?

![](https://user-images.githubusercontent.com/15085666/220139445-02458d8d-725f-4289-938c-2744872f6342.png)

See also [Matweb](https://www.matweb.com/search/datasheet_print.aspx?matguid=e7eda0f5b11243a6a9ea46f21d667dc1).

2023-02-20 14:55 UTC, Mick3Lozzo commented
@fiorisi for all the materials We have `Initial Bend Y-Factor = 0.5`

We can consider it as a sort of default value?

![](https://user-images.githubusercontent.com/15085666/220139445-02458d8d-725f-4289-938c-2744872f6342.png)

See also [Matweb](https://www.matweb.com/search/datasheet_print.aspx?matguid=e7eda0f5b11243a6a9ea46f21d667dc1).

2023-02-20 16:23 UTC, fiorisi requested changes
Thanks @Mick3Lozzo. Few more comments.
When I check the material from Creo I still see a value that probably is not the correct one.

![image](https://user-images.githubusercontent.com/8970230/220157847-81ab298e-ee57-4cd5-bd58-15a6e72e7447.png)

2023-02-21 08:15 UTC, Mick3Lozzo commented
Done @fiorisi

2023-02-21 13:23 UTC, merged

2023-02-22 13:06 UTC, fiorisi commented
@Mick3Lozzo you can not merge a PR if has not been approved. 
Please next time when changes are requested, make the changes and request another review.