adding PU 8400 material file
icub-tech-iit/cad-libraries pull request #201
Opened 2024-11-18 12:58 UTC by Mick3Lozzo

Adding PU 8400 mtl file

Data from datasheets.

[Hei-Cast PU 8400.pdf](https://github.com/user-attachments/files/17800485/Hei-Cast.PU.8400.pdf)
[PU8400 Rubber like.pdf](https://github.com/user-attachments/files/17800488/PU8400.Rubber.like.pdf)
[PU 8400 Xometry.pdf](https://github.com/user-attachments/files/17800494/PU.8400.Xometry.pdf)

2024-11-18 14:53 UTC, fiorisi requested changes

2024-11-18 14:53 UTC, fiorisi commented on config/materials/hei-cast_pu-8400.mtl
> +shore 70'
@Mick3Lozzo the shore hardness for this material can range between 60 and 90. Therefore, we should either remove this property from the description or differentiate the name based on the shore hardness.

2024-11-18 17:07 UTC, Mick3Lozzo commented
With @Lawproto we decided to rename the file to identify unmistakably the material.

2024-11-19 08:48 UTC, Lawproto requested changes

2024-11-19 08:48 UTC, Lawproto commented on config/materials/hei-cast_pu-8400_shore-70.mtl
> +Name = HEI-CAST_PU-8400
I think this should match the file name

2024-11-19 09:00 UTC, Mick3Lozzo commented on config/materials/hei-cast_pu-8400_shore-70.mtl
> +Name = HEI-CAST_PU-8400
Done.

2024-11-19 09:32 UTC, Lawproto approved these changes

2024-11-19 09:45 UTC, fiorisi approved these changes

2024-11-19 09:57 UTC, merged