Updating issue templates
icub-tech-iit/cad-libraries pull request #37
Opened 2021-06-18 09:31 UTC by fiorisi

As per title.

cc @icub-tech-iit/silo-mech

2021-06-23 11:25 UTC, marcellosavoldi commented on .github/ISSUE_TEMPLATE/Request_new_generic_libraries_CAD_part.md
> +- [ ] Added source files (STEP, IGS, etc)
Coul be interesting merge the row below:
Added source files (STEP, IGS, etc or\and datasheet, drawing etc )

2021-06-23 11:25 UTC, marcellosavoldi commented on .github/ISSUE_TEMPLATE/Request_new_generic_libraries_CAD_part.md
> +- [ ] Added link/datasheet/drawing or other informations needing to create the libraries parts
see comment above

2021-06-23 11:26 UTC, marcellosavoldi commented on .github/ISSUE_TEMPLATE/Request_new_generic_libraries_CAD_part.md
> +- [ ] File imported using the Creo [start part](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#cad-documentation-standards)
for the future, could be better convert the file using EDU-Converter

2021-06-23 11:27 UTC, marcellosavoldi requested changes
see notes.
for others all ok!

2021-06-30 11:51 UTC, fiorisi commented
@marcellosavoldi I've addressed your comments.

2021-06-30 11:52 UTC, merged